syntax = "proto3";

package telemetry.service.collector;

import "telemetry/messages/sensor_event.proto";
import "telemetry/messages/hub_event.proto";
import "google/protobuf/empty.proto";

option java_package = "ru.yandex.practicum.grpc.telemetry.collector";

enum DeviceTypeProto {
  MOTION_SENSOR = 0;      // датчик движения
  TEMPERATURE_SENSOR = 1; // датчик температуры
  LIGHT_SENSOR = 2;       // датчик освещённости
  CLIMATE_SENSOR = 3;     // датчик контроля климата
  SWITCH_SENSOR = 4;      // переключатель
}
message DeviceAddedEventProto {
  string id = 1;        // идентификатор устройства
  DeviceTypeProto type = 2; // тип устройства
}
message DeviceRemovedEventProto {
  string id = 1;        // идентификатор устройства
}
message ScenarioAddedEventProto {
  string id = 1;        // идентификатор сценария
}
message ScenarioRemovedEventProto {
  string id = 1;        // идентификатор сценария
}

service CollectorController {
  rpc CollectSensorEvent (telemetry.message.event.SensorEventProto)
      returns (google.protobuf.Empty);
  rpc CollectHubEvent (telemetry.message.event.HubEventProto)
      returns (google.protobuf.Empty);
}